#include <fcntl.h>		// For O_RDONLY
#include <sys/stat.h>		// For fstat()
#include <sys/mman.h>		// For mmap()
#include <bits/stdtr1c++.h>
#include "board.h"

#ifdef STATS
Stopwatch tLoad("Load");
#endif

//
// File globals. These parameters are common to all positions.
//
static tPos gMaxX, gMaxY, gRightx;
static size_t gBoardHeight, gBoardWidth;
static tBmp gRightmask;		// To clip cells to right edge
static tPos gGoalX, gGoalY;

Position::Position()
{
}

Position::Position(const Position &rhs) :
    fCells(rhs.fCells),
    fIntelligentX(rhs.fIntelligentX),
    fIntelligentY(rhs.fIntelligentY),
    fMoves(rhs.fMoves)
{
}

//
// Input Description: The input to the program will be from a
// text file named on the command line of the application. The
// first line will be two integers denoting the dimensions
// of the grid, number of rows and number of columns. For
// consistency and shared point of reference, the upper left
// corner of the grid will be at the (1 1) location. The second
// line of the file will be the coordinates of the goal grid
// point. The third line will be the initial coordinates of the
// intelligent cell. Remaining lines will be the coordinates of
// the remainder of the "alive" cells in the initial state of
// the game. Each line of the file will contain 10 integers
// with at least one space between each. These represent
// coordinate pairs of five alive nodes. A tag of two zeroes
// (0 0) denotes the end of the live cell coordinates. The
// exception for 10 integers per line will last line of the
// file which may have fewer than 5 coordinates and the tag.
//

void Position::load(const char *const fname)
{
    TIMER_START(tLoad);
    int fd = open(fname, O_RDONLY);
    if (fd < 0) {
	perror(fname);
	exit(-1);
    }

    /* Get the size of the file. */
    struct stat s;
    int status = fstat(fd, &s);
    int size = s.st_size;

    const char *map = (char *)mmap(0, size, PROT_READ, MAP_PRIVATE, fd, 0);
    f = map;
    if (!f) {
	perror(fname);
	exit(-1);
    }

    gMaxY = getNextPos() - 1;
    gMaxX = getNextPos() - 1;
    gGoalY = getNextPos() - 1;
    gGoalX = getNextPos() - 1;

    // Clear board
    gBoardHeight = gMaxY + 1;
    gBoardWidth = gMaxX / BMPSIZE + 1;
    gRightx = gMaxX & XCELLMASK;
    gRightmask = ~((tBmp)0) >> (BMPSIZE - ((gMaxX + 1) & XBMPMASK));
    fCells.resize(gBoardHeight * gBoardWidth, 0);

    // Populate board
    tPos x, y;
    y = getNextPos();
    x = getNextPos();
    fIntelligentY = y - 1;
    fIntelligentX = x - 1;
    while (x != 0 || y != 0) {
	fCells[(y - 1) * gBoardWidth + ((x - 1) / BMPSIZE)] |= 1ULL << ((x - 1) & XBMPMASK);
	y = getNextPos();
	x = getNextPos();
    }
    munmap(const_cast<char *>(map), size);
    TIMER_STOP(tLoad);
}

tPos Position::getNextPos()
{
    uint32_t s0, s1, s2, s3;

    // Anything that's not a decimal digit is a delimiter.
    // Skip leading delimiters.
    do
	s0 = static_cast<uint32_t>(*f++) - '0';
    while (s0 >= 10);

    // Enter loop with s0 set to digit just read
    tPos result = 0;
    for (;;) {
	s1 = static_cast<uint32_t>(*f++) - '0';
	if (s1 >= 10)
	    return result + s0;
	s2 = static_cast<uint32_t>(*f++) - '0';
	if (s2 >= 10)
	    return result + s0 * 10 + s1;
	s3 = static_cast<uint32_t>(*f++) - '0';
	if (s3 >= 10)
	    return result + s0 * 100 + s1 * 10 + s2;

	result += s0 * 1000 + s1 * 100 + s2 * 10 + s3;
	s0 = static_cast<uint32_t>(*f++) - '0';
	if (s0 >= 10)
	    return result;
	result *= 10000;
    }
}

// 
// The output to be generated by the application is a list of moves
// executed by the intelligent cell to reach the goal point. Each
// single move will be described by an integer digit from '0' to '8'. A
// move that leaves the intelligent cell on the current grid point
// is represented by '0'; for location changes, the eight surrounding
// cells are numbered consecutively starting in the upper left corner
// (diagonal) with '1' and proceeding clockwise to '8'. (For example,
// a move up (North) would be designated by a '2' and diagonal move down
// and to the right (Southeast) would be designated with a '5'.) Lines
// in the output file will contain 40 digits, no spaces in between,
// with the last line possibly being less than 40 characters. If there
// is no possible solution to the given puzzle, the output file should
// contain a message to state that fact.
// 
void Position::output(BoardStats *t, FILE *fp, const int dir)
{
    if (dir >= 0)
	fMoves.push_back('0' + dir);
    output(t, fp, fMoves.c_str());
}

void Position::output(BoardStats *t, FILE *fp, const char *s)
{
    TIMER_START(t->tOutput);
    int n = strlen(s);
    for (int i = 0; i < n; i += 40, s += 40) {
	fprintf(fp, "%.40s\n", s);
    }
    TIMER_STOP(t->tOutput);
}


//
// For debugging, print the current state of the board.
//
void Position::print()
{
    tPos x, y;

    printf("%d x %d board. Intelligent cell (%d, %d). Goal (%d, %d). Moves %s\n",
	gMaxX + 1,
	gMaxY + 1,
	fIntelligentX,
	fIntelligentY,
	gGoalX,
	gGoalY,
	fMoves.c_str());
    tBmp *p;
    for (y = 0, p = &fCells[0]; y < gBoardHeight; ++y) {
	for (x = 0; x <= gMaxX; x += BMPSIZE, ++p)
	    printFilledColumn(x, y, *p);
	putchar('\n');
    }
}

void Position::printFilledColumn(tPos x, tPos y, tBmp b) const
{
    for (int i = 0; i < BMPSIZE && x <= gMaxX; ++i, ++x, b >>= 1) {
	if (y == fIntelligentY && x == fIntelligentX)
	    putchar('I');
	else if (y == gGoalY && x == gGoalX)
	    putchar((b & 1) != 0 ? 'G' : 'g');
	else if ((b & 1) != 0)
	    putchar('*');
	else
	    putchar('.');
    }
}

uint32_t Position::distance(const int dir) const
{
    int x = fIntelligentX;
    int y = fIntelligentY;

    switch (dir) {
    case 0: break;
    case 1: --x; --y; break;
    case 2: --y; break;
    case 3: ++x; --y; break;
    case 4: ++x; break;
    case 5: ++x; ++y; break;
    case 6: ++y; break;
    case 7: --x; ++y; break;
    case 8: --x; break;
    }

    int dx = gGoalX - x;
    int dy = gGoalY - y;

    if (dx < 0) dx = -dx;
    if (dy < 0) dy = -dy;
    return dx > dy ? dx : dy;
}

//
// Add one bit values in parallel.
// a0 and a1 are packed vectors of bits.
// Calculate b = a0 + a1
// Because it takes two bits to represent 1 + 1, let b0 be the lsb
// of the sum and b1 the msb.
//
inline void Position::ADD2(tBmp &b0, tBmp &b1, const tBmp a0, const tBmp a1) const
{
    b1 = a0 & a1;
    b0 = a0 ^ a1;
}

//
// Add one bit values in parallel.
// a0, a1 and a2 are packed vectors of bits.
// Calculate b = a0 + a1 + a2
// Because it takes two bits to represent 2 or 3, let b0 be the lsb
// of the sum and b1 the msb.
//
inline void Position::ADD3(tBmp &b0, tBmp &b1,
    const tBmp a0, const tBmp a1, const tBmp a2) const
{
    tBmp t0, t1;
    ADD2(b0, t0, a0, a1);
    ADD2(b0, t1, b0, a2);
    b1 = t0 | t1;
}

//
// Shift a0 one bit to the left, rotating in the msb of a1 from the right.
//
inline tBmp Position::ROL(const tBmp a0, const tBmp a1) const
{
    return a0 << 1 | a1 >> BMPSIZE-1;
}

//
// Shift a0 one bit to the right, rotating in the lsb of a1 from the left.
//
inline tBmp Position::ROR(const tBmp a0, const tBmp a1) const
{
    return a0 >> 1 | a1 << BMPSIZE-1;
}

//
// Updates fCells to next generation following Game of Life rules.
// Returns false if intelligent cell would die (fCells unnaffected)
// Reference:
// http://dotat.at/prog/life/life.html
// http://dotat.at/prog/life/life.c
// Watch out. His X-coords may be backwards.
//
Position *Position::nextgen(BoardStats *t, const int dir)
{
    TIMER_START(t->tNextGen);
    Position *ret = new Position(*this);

    ret->fMoves.push_back('0' + dir);

    tPos yold = fIntelligentY;
    tPos xcellold = fIntelligentX & XCELLMASK;
    tBmp xbitold = ~(1ULL << (fIntelligentX & XBMPMASK));

    switch (dir) {
    case 0: break;
    case 1: --ret->fIntelligentX; --ret->fIntelligentY; break;
    case 2: --ret->fIntelligentY; break;
    case 3: ++ret->fIntelligentX; --ret->fIntelligentY; break;
    case 4: ++ret->fIntelligentX; break;
    case 5: ++ret->fIntelligentX; ++ret->fIntelligentY; break;
    case 6: ++ret->fIntelligentY; break;
    case 7: --ret->fIntelligentX; ++ret->fIntelligentY; break;
    case 8: --ret->fIntelligentX; break;
    }

    tPos ynew = ret->fIntelligentY;
    tPos xcellnew = ret->fIntelligentX & XCELLMASK;
    tBmp xbitnew = 1ULL << (ret->fIntelligentX & XBMPMASK);

    //
    // Output next generation to ret->fCells.
    //
    tBmp *p = &ret->fCells[0];
    const tBmp *prev, *curr, *next;
    register tBmp prevmid, currmid, nextmid;
    tBmp rear0, rear1;
    prevmid = currmid = nextmid = rear0 = rear1 = 0;

    //
    // Outer loop scans y from top to bottom.
    // When we're outputting cells on row y:
    //     curr points to old cells on row y
    //     prev points to row y-1
    //     next points to row y+1
    // If any of those input rows are empty then prev, curr and/or next
    // will be NULL.
    //
    prev = 0;
    curr = &fCells[0];
    next = &fCells[gBoardWidth];
    for (tPos ycurr = 0; ycurr <= gMaxY; ++ycurr) {
	if (ycurr == 1)
	    prev = &fCells[0];
	if (ycurr == gMaxY)
	    next = 0;

	//
	// Secondary loop scans x from left to right
	//
	for (tPos xmid = -BMPSIZE; xmid <= gMaxX; xmid += BMPSIZE) {
	    tPos xfore = xmid + BMPSIZE;

	    //
	    // Set bitmaps prevfore, currfore and nextfore to next column to the right.
	    // They are aligned vertically from top to bottom.
	    // Some or all may be empty.
	    //
	    register tBmp prevfore, currfore, nextfore;
	    prevfore = currfore = nextfore = 0;
	    if (xfore <= gMaxX) {
		if (prev)
		    prevfore = *prev++;
		currfore = *curr++;
		if (next)
		    nextfore = *next++;
	    }

	    if (dir != 0) {
		//
		// Clear old intelligent cell
		//
		if (xfore == xcellold) {
		    if (ycurr-1 == yold)
			prevfore &= xbitold;
		    else if (ycurr == yold)
			currfore &= xbitold;
		    else if (ycurr+1 == yold)
			nextfore &= xbitold;
		}

		//
		// Set new intelligent cell
		//
		if (xfore == xcellnew) {
		    if (ycurr-1 == ynew)
			prevfore |= xbitnew;
		    else if (ycurr == ynew)
			currfore |= xbitnew;
		    else if (ycurr+1 == ynew)
			nextfore |= xbitnew;
		}
	    }

	    if (xmid >= 0) {
		//
		// Let count0, count1, and count2 be bits 0-2 of the
		// neighbor counts for the set of cells under consideration.
		// Don't bother calculating bit 3 because it's only set
		// when a cell has 8 neighbors. The cell will die whenever
		// bit 2 gets set (4 or more neighbors) so catch large
		// counts at that point.
		//
		tBmp mid0, mid1, fore0, fore1;
		tBmp count0, count1, count2a, count2b;
		ADD3(fore0, fore1, ROR(prevmid, prevfore),
				   ROR(currmid, currfore),
				   ROR(nextmid, nextfore));
		ADD2(mid0, mid1, prevmid, nextmid);
		ADD3(count0, count1, fore0, mid0, rear0);
		ADD3(count1, count2a, count1, fore1, rear1);
		ADD2(count1, count2b, count1, mid1);

		//
		// Let bmp be the new state of the cells. OR the current
		// state of the cell to the neighbor count to handle both
		// the living rule (2 or 3 neighbors) and the spontaneous
		// generation rule (3 neighbors).
		//
		tBmp bmp = (count0 | currmid) & count1 &
		    ~count2a & ~count2b;	// Mask those with 4+ neighbors

		//
		// Clip bmp to right boundary and output it.
		//
		if (xmid == gRightx)
		    bmp &= gRightmask;
		*p++ = bmp;
	    }

	    //
	    // Pre-calculate rear neighbor counts for next iteration.
	    // This way we don't need to keep rear bitmaps around.
	    //
	    ADD3(rear0, rear1, ROL(prevfore, prevmid),
			       ROL(currfore, currmid),
			       ROL(nextfore, nextmid));

	    //
	    // Advance to the right.
	    // Foreward bitmaps become middle bitmaps.
	    //
	    prevmid = prevfore;
	    currmid = currfore;
	    nextmid = nextfore;
	}
    }

    TIMER_STOP(t->tNextGen);
    return ret;
}

//
// Output set of directions (0 through 8) of legal moves for intelligent cell.
// A move is legal if:
// 1. It stays in bounds
// 2. Moves to a cell that is currently unoccupied
// 3. Will survive next generation
//
std::vector<int> Position::legalMoves(BoardStats *t) const
{
    TIMER_START(t->tLegalMoves);
    //
    // Mask out intelligent cell
    // Perform neighbor count
    // Set output bit if both:
    // 1. Cell was unoccupied
    // 2. Will survive if occubied by intelligent cell
    //
    const tBmp *prev, *curr, *next;

    tPos ycurr;
    tPos ylast = 1;				// Previous y value output
    tPos xdiv = fIntelligentX & XCELLMASK;	// Cache intelligent location
    tBmp xmask = ~(1ULL << (fIntelligentX & XBMPMASK));

    std::vector<int> directions;
    directions.reserve(9);
    tPos yi = fIntelligentY;
    tPos yn = fIntelligentY - 1;
    tPos ys = fIntelligentY + 1;
    tPos xw = fIntelligentX - 1;
    tPos xe = fIntelligentX + 1;
    tPos xidiv = fIntelligentX & XCELLMASK;
    tPos xwdiv = xw & XCELLMASK;
    tPos xediv = xe & XCELLMASK;
    tBmp ximask = (1UL << (fIntelligentX & XBMPMASK));
    tBmp xwmask = (1UL << (xw & XBMPMASK));
    tBmp xemask = (1UL << (xe & XBMPMASK));

    tPos ynclamp = (yn < 0) ? 0 : yn;
    tPos ynnclamp = (ynclamp - 1 < 0) ? 0 : ynclamp - 1;
    tPos ysclamp = (ys > gMaxY) ? gMaxY : ys;
    tPos xwclamp = (xw < 0) ? 0 : xw;
    tPos xeeclamp = (xe + 1 > gMaxX) ? gMaxX : xe + 1;
    tPos xwclampdiv = xwclamp & XCELLMASK;
    tPos xeeclampdiv = xeeclamp & XCELLMASK;

    register tBmp prevmid, currmid, nextmid;
    tBmp rear0, rear1;
    prevmid = currmid = nextmid = rear0 = rear1 = 0;

    prev = (ynclamp - 1 < 0) ? 0 : &fCells[(ynclamp - 1) * gBoardWidth];
    curr = (ynclamp < 0) ? 0 : &fCells[ynclamp * gBoardWidth];
    next = &fCells[(ynclamp + 1) * gBoardWidth];
    for (ycurr = ynclamp; ycurr <= ysclamp; ++ycurr) {
	if (ycurr == 1)
	    prev = &fCells[0];
	if (ycurr == gMaxY)
	    next = 0;

	//
	// Secondary loop scans x from left to right
	//
	for (tPos xmid = -BMPSIZE; xmid <= gMaxX; xmid += BMPSIZE) {
	    //
	    // Set bitmaps prevfore, currfore and nextfore.
	    // They are aligned vertically from top to bottom.
	    // Some or all may be empty.
	    //
	    register tBmp prevfore, currfore, nextfore;
	    prevfore = currfore = nextfore = 0;
	    if (xmid + BMPSIZE <= gMaxX) {
		if (prev)
		    prevfore = *prev++;
		currfore = *curr++;
		if (next)
		    nextfore = *next++;
	    }

	    //
	    // Mask out intelligent cell from fore.
	    // It will automatically slide to mid later.
	    //
	    if (xmid + BMPSIZE == xdiv) {
		if (ycurr-1 == fIntelligentY)
		    prevfore &= xmask;
		else if (ycurr == fIntelligentY)
		    currfore &= xmask;
		else if (ycurr+1 == fIntelligentY)
		    nextfore &= xmask;
	    }

	    if (xmid >= 0) {
		//
		// Let count0, count1, and count2 be bits 0-2 of the
		// neighbor counts for the set of cells under consideration.
		// Don't bother calculating bit 3 because it's only set
		// when a cell has 8 neighbors. The cell will die whenever
		// bit 2 gets set (4 or more neighbors) so catch large
		// counts at that point.
		//
		tBmp mid0, mid1, fore0, fore1;
		tBmp count0, count1, count2a, count2b;
		ADD3(fore0, fore1, ROR(prevmid, prevfore),
				   ROR(currmid, currfore),
				   ROR(nextmid, nextfore));
		ADD2(mid0, mid1, prevmid, nextmid);
		ADD3(count0, count1, fore0, mid0, rear0);
		ADD3(count1, count2a, count1, fore1, rear1);
		ADD2(count1, count2b, count1, mid1);

		//
		// Let bmp be the legal places to move. Exclude any bits
		// set in the current state because they're already
		// occupied. Include those with bit 1 of the neighbor
		// count set because that's 2 or 3. Exclude those with
		// bit 2 set - too many neighbors.
		//
		tBmp bmp = ~currmid & count1 &
		    ~count2a & ~count2b;	// Mask those with 4+ neighbors

		//
		// If bmp is non-zero, examine it for 1 bits in
		// vicinity of intelligent cell. Save legal moves
		// in directions container.
		//
		if (bmp) {
		    if (ycurr == yn) {
			if (xmid == xwdiv && (bmp & xwmask) != 0)
			    directions.push_back(1);
			if (xmid == xidiv && (bmp & ximask) != 0)
			    directions.push_back(2);
			if (xmid == xediv && (bmp & xemask) != 0)
			    directions.push_back(3);
		    }
		    else if (ycurr == fIntelligentY) {
			if (xmid == xwdiv && (bmp & xwmask) != 0)
			    directions.push_back(8);
			if (xmid == xidiv && (bmp & ximask) != 0)
			    directions.push_back(0);
			if (xmid == xediv && (bmp & xemask) != 0)
			    directions.push_back(4);
		    }
		    else if (ycurr == ys) {
			if (xmid == xwdiv && (bmp & xwmask) != 0)
			    directions.push_back(7);
			if (xmid == xidiv && (bmp & ximask) != 0)
			    directions.push_back(6);
			if (xmid == xediv && (bmp & xemask) != 0)
			    directions.push_back(5);
		    }
		}
	    }

	    //
	    // Pre-calculate rear neighbor counts for next iteration.
	    // This way we don't need to keep rear bitmaps around.
	    //
	    ADD3(rear0, rear1, ROL(prevfore, prevmid),
			       ROL(currfore, currmid),
			       ROL(nextfore, nextmid));

	    //
	    // Advance to the right.
	    // Foreward bitmaps become middle bitmaps.
	    //
	    prevmid = prevfore;
	    currmid = currfore;
	    nextmid = nextfore;
        }
    }

    TIMER_STOP(t->tLegalMoves);
    return directions;
}
