#include <cstring>		// For strlen()
#include "board.h"

#ifdef STATS
Stopwatch tLoad("Load");
#endif

//
// These parameters are common to all positions.
//
tPos Position::gMaxX, Position::gMaxY, Position::gRightx;
size_t Position::gBoardHeight, Position::gBoardWidth;
tBmp Position::gRightmask;
tPos Position::gGoalX, Position::gGoalY;

//
// Convert move direction to delta x and delta y.
//
std::pair<int, int> Position::fDelta[] = {
    {0, 0},     // stand pat
    {-1, -1},   // northwest
    {0, -1},    // north
    {1, -1},    // northeast
    {1, 0},     // east
    {1, 1},     // southeast
    {0, 1},     // south
    {-1, 1},    // soutwest
    {-1, 0}     // west
};

// 
// The output to be generated by the application is a list of moves
// executed by the intelligent cell to reach the goal point. Each
// single move will be described by an integer digit from '0' to '8'. A
// move that leaves the intelligent cell on the current grid point
// is represented by '0'; for location changes, the eight surrounding
// cells are numbered consecutively starting in the upper left corner
// (diagonal) with '1' and proceeding clockwise to '8'. (For example,
// a move up (North) would be designated by a '2' and diagonal move down
// and to the right (Southeast) would be designated with a '5'.) Lines
// in the output file will contain 40 digits, no spaces in between,
// with the last line possibly being less than 40 characters. If there
// is no possible solution to the given puzzle, the output file should
// contain a message to state that fact.
// 
void Position::output(BoardStats &t, FILE *fp, const char dir)
{
    if (dir >= '0')
	fMoves.push_back(dir);
    output(t, fp, std::move(fMoves));
}

void Position::output(BoardStats &t, FILE *fp, std::string &&s)
{
    TIMER_START(t.tOutput);
    int n;
    const char *p = s.c_str();
    for (n = s.length(); n > 40; n -= 40, p += 40) {
        fwrite(p, 1, 40, fp);
        fputc('\n', fp);
    }
    fwrite(p, 1, n, fp);
    fputc('\n', fp);
    TIMER_STOP(t.tOutput);
}


#ifdef DEBUG
//
// For debugging, print the current state of the board.
//
void Position::print()
{
    tPos x, y;

    printf("%d x %d board. Intelligent cell (%d, %d). Goal (%d, %d). Moves %s\n",
	gMaxX + 1,
	gMaxY + 1,
	fIntelligentX,
	fIntelligentY,
	gGoalX,
	gGoalY,
	fMoves.c_str());
    tBmp *p;
    for (y = 0, p = &fCells[0]; y < gBoardHeight; ++y) {
	for (x = 0; x <= gMaxX; x += BMPSIZE, ++p)
	    printFilledColumn(x, y, *p);
	putchar('\n');
    }
}

void Position::printFilledColumn(tPos x, tPos y, tBmp b) const
{
    for (int i = 0; i < BMPSIZE && x <= gMaxX; ++i, ++x, b >>= 1) {
	if (y == fIntelligentY && x == fIntelligentX)
	    putchar('I');
	else if (y == gGoalY && x == gGoalX)
	    putchar((b & 1) != 0 ? 'G' : 'g');
	else if ((b & 1) != 0)
	    putchar('*');
	else
	    putchar('.');
    }
}
#endif

uint32_t Position::distance(const char dir) const
{
    int x = fIntelligentX;
    int y = fIntelligentY;

    const std::pair<int, int> &delta = fDelta[dir - '0'];
    x += delta.first;
    y += delta.second;

    int dx = gGoalX - x;
    int dy = gGoalY - y;

    if (dx < 0) dx = -dx;
    if (dy < 0) dy = -dy;
    return dx > dy ? dx : dy;
}

//
// Updates fCells to next generation following Game of Life rules.
// Returns false if intelligent cell would die (fCells unnaffected)
// Reference:
// http://dotat.at/prog/life/life.html
// http://dotat.at/prog/life/life.c
// Watch out. His X-coords may be backwards.
//
Position *Position::nextgen(BoardStats &t, const char dir)
{
    TIMER_START(t.tNextGen);
    Position *ret = new Position(*this);

    ret->fMoves.push_back(dir);

    tPos yold = fIntelligentY;
    tPos xcellold = fIntelligentX & XCELLMASK;
    tBmp xbitold = ~(1ULL << (fIntelligentX & XBMPMASK));

    const std::pair<int, int> &delta = fDelta[dir - '0'];
    ret->fIntelligentX += delta.first;
    ret->fIntelligentY += delta.second;

    tPos ynew = ret->fIntelligentY;
    tPos xcellnew = ret->fIntelligentX & XCELLMASK;
    tBmp xbitnew = 1ULL << (ret->fIntelligentX & XBMPMASK);

    //
    // Output next generation to ret->fCells.
    //
    tBmp *p = &ret->fCells[0];
    const tBmp *prev, *curr, *next;
    register tBmp prevmid, currmid, nextmid;
    tBmp rear0, rear1;
    prevmid = currmid = nextmid = rear0 = rear1 = 0;

    //
    // Outer loop scans y from top to bottom.
    // When we're outputting cells on row y:
    //     curr points to old cells on row y
    //     prev points to row y-1
    //     next points to row y+1
    // If any of those input rows are empty then prev, curr and/or next
    // will be NULL.
    //
    prev = 0;
    curr = &fCells[0];
    next = &fCells[gBoardWidth];
    for (tPos ycurr = 0; ycurr <= gMaxY; ++ycurr) {
	if (ycurr == 1)
	    prev = &fCells[0];
	if (ycurr == gMaxY)
	    next = 0;

	//
	// Secondary loop scans x from left to right
	//
	for (tPos xmid = -BMPSIZE; xmid <= gMaxX; xmid += BMPSIZE) {
	    tPos xfore = xmid + BMPSIZE;

	    //
	    // Set bitmaps prevfore, currfore and nextfore to next column to the right.
	    // They are aligned vertically from top to bottom.
	    // Some or all may be empty.
	    //
	    register tBmp prevfore, currfore, nextfore;
	    prevfore = currfore = nextfore = 0;
	    if (xfore <= gMaxX) {
		if (prev)
		    prevfore = *prev++;
		currfore = *curr++;
		if (next)
		    nextfore = *next++;
	    }

	    if (dir != '0') {
		//
		// Clear old intelligent cell
		//
		if (xfore == xcellold) {
		    if (ycurr-1 == yold)
			prevfore &= xbitold;
		    else if (ycurr == yold)
			currfore &= xbitold;
		    else if (ycurr+1 == yold)
			nextfore &= xbitold;
		}

		//
		// Set new intelligent cell
		//
		if (xfore == xcellnew) {
		    if (ycurr-1 == ynew)
			prevfore |= xbitnew;
		    else if (ycurr == ynew)
			currfore |= xbitnew;
		    else if (ycurr+1 == ynew)
			nextfore |= xbitnew;
		}
	    }

	    if (xmid >= 0) {
		//
		// Let count0, count1, and count2 be bits 0-2 of the
		// neighbor counts for the set of cells under consideration.
		// Don't bother calculating bit 3 because it's only set
		// when a cell has 8 neighbors. The cell will die whenever
		// bit 2 gets set (4 or more neighbors) so catch large
		// counts at that point.
		//
		tBmp mid0, mid1, fore0, fore1;
		tBmp count0, count1, count2a, count2b;
		ADD3(fore0, fore1, ROR(prevmid, prevfore),
				   ROR(currmid, currfore),
				   ROR(nextmid, nextfore));
		ADD2(mid0, mid1, prevmid, nextmid);
		ADD3(count0, count1, fore0, mid0, rear0);
		ADD3(count1, count2a, count1, fore1, rear1);
		ADD2(count1, count2b, count1, mid1);

		//
		// Let bmp be the new state of the cells. OR the current
		// state of the cell to the neighbor count to handle both
		// the living rule (2 or 3 neighbors) and the spontaneous
		// generation rule (3 neighbors).
		//
		tBmp bmp = (count0 | currmid) & count1 &
		    ~count2a & ~count2b;	// Mask those with 4+ neighbors

		//
		// Clip bmp to right boundary and output it.
		//
		if (xmid == gRightx)
		    bmp &= gRightmask;
		*p++ = bmp;
	    }

	    //
	    // Pre-calculate rear neighbor counts for next iteration.
	    // This way we don't need to keep rear bitmaps around.
	    //
	    ADD3(rear0, rear1, ROL(prevfore, prevmid),
			       ROL(currfore, currmid),
			       ROL(nextfore, nextmid));

	    //
	    // Advance to the right.
	    // Foreward bitmaps become middle bitmaps.
	    //
	    prevmid = prevfore;
	    currmid = currfore;
	    nextmid = nextfore;
	}
    }

    TIMER_STOP(t.tNextGen);
    return ret;
}

//
// Output set of directions (0 through 8) of legal moves for intelligent cell.
// A move is legal if:
// 1. It stays in bounds
// 2. Moves to a cell that is currently unoccupied
// 3. Will survive next generation
//
std::string Position::legalMoves(BoardStats &t) const
{
    TIMER_START(t.tLegalMoves);
    //
    // Mask out intelligent cell
    // Perform neighbor count
    // Set output bit if both:
    // 1. Cell was unoccupied
    // 2. Will survive if occubied by intelligent cell
    //
    const tBmp *prev, *curr, *next;

    tPos ycurr;
    tPos ylast = 1;				// Previous y value output
    tPos xdiv = fIntelligentX & XCELLMASK;	// Cache intelligent location
    tBmp xmask = ~(1ULL << (fIntelligentX & XBMPMASK));

    std::string directions;
    tPos yi = fIntelligentY;
    tPos yn = fIntelligentY - 1;
    tPos ys = fIntelligentY + 1;
    tPos xw = fIntelligentX - 1;
    tPos xe = fIntelligentX + 1;
    tPos xidiv = fIntelligentX & XCELLMASK;
    tPos xwdiv = xw & XCELLMASK;
    tPos xediv = xe & XCELLMASK;
    tBmp ximask = (1UL << (fIntelligentX & XBMPMASK));
    tBmp xwmask = (1UL << (xw & XBMPMASK));
    tBmp xemask = (1UL << (xe & XBMPMASK));

    tPos ynclamp = (yn < 0) ? 0 : yn;
    tPos ynnclamp = (ynclamp - 1 < 0) ? 0 : ynclamp - 1;
    tPos ysclamp = (ys > gMaxY) ? gMaxY : ys;
    tPos xwclamp = (xw < 0) ? 0 : xw;
    tPos xeeclamp = (xe + 1 > gMaxX) ? gMaxX : xe + 1;
    tPos xwclampdiv = xwclamp & XCELLMASK;
    tPos xeeclampdiv = xeeclamp & XCELLMASK;

    register tBmp prevmid, currmid, nextmid;
    tBmp rear0, rear1;
    prevmid = currmid = nextmid = rear0 = rear1 = 0;

    prev = (ynclamp - 1 < 0) ? 0 : &fCells[(ynclamp - 1) * gBoardWidth];
    curr = (ynclamp < 0) ? 0 : &fCells[ynclamp * gBoardWidth];
    next = &fCells[(ynclamp + 1) * gBoardWidth];
    for (ycurr = ynclamp; ycurr <= ysclamp; ++ycurr) {
	if (ycurr == 1)
	    prev = &fCells[0];
	if (ycurr == gMaxY)
	    next = 0;

	//
	// Secondary loop scans x from left to right
	//
	for (tPos xmid = -BMPSIZE; xmid <= gMaxX; xmid += BMPSIZE) {
	    //
	    // Set bitmaps prevfore, currfore and nextfore.
	    // They are aligned vertically from top to bottom.
	    // Some or all may be empty.
	    //
	    register tBmp prevfore, currfore, nextfore;
	    prevfore = currfore = nextfore = 0;
	    if (xmid + BMPSIZE <= gMaxX) {
		if (prev)
		    prevfore = *prev++;
		currfore = *curr++;
		if (next)
		    nextfore = *next++;
	    }

	    //
	    // Mask out intelligent cell from fore.
	    // It will automatically slide to mid later.
	    //
	    if (xmid + BMPSIZE == xdiv) {
		if (ycurr-1 == fIntelligentY)
		    prevfore &= xmask;
		else if (ycurr == fIntelligentY)
		    currfore &= xmask;
		else if (ycurr+1 == fIntelligentY)
		    nextfore &= xmask;
	    }

	    if (xmid >= 0) {
		//
		// Let count0, count1, and count2 be bits 0-2 of the
		// neighbor counts for the set of cells under consideration.
		// Don't bother calculating bit 3 because it's only set
		// when a cell has 8 neighbors. The cell will die whenever
		// bit 2 gets set (4 or more neighbors) so catch large
		// counts at that point.
		//
		tBmp mid0, mid1, fore0, fore1;
		tBmp count0, count1, count2a, count2b;
		ADD3(fore0, fore1, ROR(prevmid, prevfore),
				   ROR(currmid, currfore),
				   ROR(nextmid, nextfore));
		ADD2(mid0, mid1, prevmid, nextmid);
		ADD3(count0, count1, fore0, mid0, rear0);
		ADD3(count1, count2a, count1, fore1, rear1);
		ADD2(count1, count2b, count1, mid1);

		//
		// Let bmp be the legal places to move. Exclude any bits
		// set in the current state because they're already
		// occupied. Include those with bit 1 of the neighbor
		// count set because that's 2 or 3. Exclude those with
		// bit 2 set - too many neighbors.
		//
		tBmp bmp = ~currmid & count1 &
		    ~count2a & ~count2b;	// Mask those with 4+ neighbors

		//
		// If bmp is non-zero, examine it for 1 bits in
		// vicinity of intelligent cell. Save legal moves
		// in directions string.
		//
		if (bmp) {
		    if (ycurr == yn) {
			if (xmid == xwdiv && (bmp & xwmask) != 0)
			    directions.push_back('1');
			if (xmid == xidiv && (bmp & ximask) != 0)
			    directions.push_back('2');
			if (xmid == xediv && (bmp & xemask) != 0)
			    directions.push_back('3');
		    }
		    else if (ycurr == fIntelligentY) {
			if (xmid == xwdiv && (bmp & xwmask) != 0)
			    directions.push_back('8');
			if (xmid == xidiv && (bmp & ximask) != 0)
			    directions.push_back('0');
			if (xmid == xediv && (bmp & xemask) != 0)
			    directions.push_back('4');
		    }
		    else if (ycurr == ys) {
			if (xmid == xwdiv && (bmp & xwmask) != 0)
			    directions.push_back('7');
			if (xmid == xidiv && (bmp & ximask) != 0)
			    directions.push_back('6');
			if (xmid == xediv && (bmp & xemask) != 0)
			    directions.push_back('5');
		    }
		}
	    }

	    //
	    // Pre-calculate rear neighbor counts for next iteration.
	    // This way we don't need to keep rear bitmaps around.
	    //
	    ADD3(rear0, rear1, ROL(prevfore, prevmid),
			       ROL(currfore, currmid),
			       ROL(nextfore, nextmid));

	    //
	    // Advance to the right.
	    // Foreward bitmaps become middle bitmaps.
	    //
	    prevmid = prevfore;
	    currmid = currfore;
	    nextmid = nextfore;
        }
    }

    TIMER_STOP(t.tLegalMoves);
    return directions;
}
