#include "output.h"
#include "powers.h"

//
// Globals
//
FILE *OutputFile::fp;
pthread_mutex_t OutputFile::fpMutex = PTHREAD_MUTEX_INITIALIZER;
bool OutputFile::noresults = true;

//
// Output Description:
// The output to be generated by the application is a list of consecutive
// primes and the perfect power that is the sum of those primes. To
// shorten the output, only the first and last prime of the consecutive
// primes need be printed. The sum and how the sum is a perfect prime
// must be printed. Output for the application will be stored in the
// text file specified as the fourth parameter on the command line. If
// there are no consecutive prime sums (within the input range) that
// equal a perfect power (within the exponent range), then a message
// to state that fact should be written to the output file.
//
// Example output file:
// sum(3:5) = 8 = 2**3
// sum(17:19) = 36 = 6**2
// sum(2:23) = 100 = 10**2
// sum(13:19) = 49 = 7**2
// sum(5:13) = 36 = 6**2
//
// This function usually just sprintfs into the current buffer.
// If full and mutex is available, flush all buffers to output file.
// Otherwise, allocate another buffer and chain it.
//

OutputFile::OutputFile() : freelist(NULL)
{
    head = tail = bufalloc();
}

//
// Destructor does final flush (if necessary).
// All the caller has to do is let OutputFile go out of scope.
//
OutputFile::~OutputFile()
{
    if (avail < BUFSIZE) {              // if there's something left to flush
        pthread_mutex_lock(&fpMutex);
        bufflush();
    }
}

//
// Prints one line of output into buffer.
// May flush buffer if full and the mutex is readily available.
//
// Note that firstprime and lastprime are asymmetric:
//     firstprime is given by: p[1] - p[0]
//     lastprime equals:       p[0] - p[-1]
// This is for the convenience of the serach strategies. They prefer
// to deal in k-pair runs where sum = *right - *left
//
void OutputFile::printresult(const tSum *firstprime, const tSum *lastprime,
    const PerfectPower *power)
{
    //
    // Worst case line of output would be like:
    // sum(1234567890:2345678901) = 576460752303423488 = 123456789**10
    // That's 64 characters including the nul.
    //
    if (avail < 64) {
        if (pthread_mutex_trylock(&fpMutex) == 0)
            bufflush();
        else
            tail = tail->next = bufalloc();
    }

    int n = sprintf(s, "sum(%lu:%lu) = %lu = %u**%u\n",
        firstprime[1] - firstprime[0],
        lastprime[0] - lastprime[-1],
        power->n, power->base, power->exp);
    s += n;
    avail -= n;
}

//
// Allocate a new OutputBuffer from the freelist or the heap.
// Set s and avail to reference the new buffer.
//
OutputFile::OutputBuffer *OutputFile::bufalloc()
{
    OutputBuffer *p;
    if (freelist) {
        p = freelist;
        freelist = freelist->next;
    }
    else
        p = new OutputBuffer;
    p->next = NULL;
    s = p->buf;
    avail = BUFSIZE;
    return p;
}

//
// Only call with mutex locked. It will unlock and return.
//
// Flushes all buffers to output file.
// Leaves one empty block at head/tail.
// Moves the rest to the freelist.
// Resets s and avail.
//
void OutputFile::bufflush()
{
    for (;;) {
        fputs(head->buf, fp);
        OutputBuffer *pnext = head->next;
        if (!pnext)
            break;
        else {
            head->next = freelist;
            freelist = head;
            head = pnext;
        }
    }
    pthread_mutex_unlock(&fpMutex);     // End of critical section

    noresults = false;
    tail = head;
    s = tail->buf;
    avail = BUFSIZE;
}
